---
- name: restart minidlna
  systemd:
    daemon_reload: true
    name: minidlna
    state: restarted
  become: true
  tags: minidlna

- name: reload minidlna
  systemd:
    name: minidlna
    state: reloaded
  become: true
  tags: minidlna